spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://mysql:3346/hhplus_stress?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20               # 풀 크기를 20으로 설정
      minimum-idle: 10                    # 최소 유휴 커넥션 수
      connection-timeout: 30000           # 커넥션 타임아웃 시간을 30초로 설정
      idle-timeout: 600000                # 유휴 커넥션 타임아웃 시간을 10분으로 설정
      max-lifetime: 1800000               # 커넥션 최대 수명을 30분으로 설정
  h2:
    console:
      enabled: true
#  sql:
#    init:
#      mode: always
#      continue-on-error: true
#      data-locations: classpath:sql/data.sql
  data:
    redis:
      host: redis
      port: 6379

# Kafka 설정 추가
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest # 초기 오프셋 설정
      enable-auto-commit: true    # 자동 커밋 활성화
      max-poll-records: 10        # 한 번에 가져올 최대 메시지 수
    template:
      default-topic: error-messages

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE

decorator:
  datasource:
    p6spy:
      enable-logging: true