spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3346/hhplus?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
      continue-on-error: true
      data-locations: classpath:sql/data.sql
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE

decorator:
  datasource:
    p6spy:
      enable-logging: true