global:
  scrape_interval: 15s  # 기본 스크랩 주기
  evaluation_interval: 15s  # 규칙 평가 주기

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'k6'
    static_configs:
      - targets: ['k6:9090']  # K6 서비스의 Prometheus 엔드포인트

remote_write:
  - url: "http://localhost:9090/api/v1/write"
    remote_timeout: 30s
    queue_config:
      capacity: 1000
      max_shards: 200
      min_shards: 1
    write_relabel_configs:
      - source_labels: [__name__]
        regex: ".*"
        action: keep
